### ISSUE TITLE
completium-cli start sandbox fails

### ISSUE THREAD

**Issue by ristiisa** [completium/completium-cli#43]
Unable to start sandbox through @completium/completium-cli@0.4.76
```
> completium-cli start sandbox
Waiting for sandbox to start ...
Error: Command failed with exit code 127: docker run --rm --name my-sandbox --cpus 1 -e block_time=10 --detach -p 20000:20000 oxheadalpha/flextesa:latest jakartabox start
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "jakartabox": executable file not found in $PATH: unknown.
a14565de2e3a549640d69675be4ca8b6ae5fe8b25d26d02938ece23501143d31
    at makeError (C:\Users\USER\AppData\Roaming\npm\node_modules\@completium\completium-cli\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\USER\AppData\Roaming\npm\node_modules\@completium\completium-cli\node_modules\execa\index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startSandbox (C:\Users\USER\AppData\Roaming\npm\node_modules\@completium\completium-cli\src\main.js:883:24)
    at async exec (C:\Users\USER\AppData\Roaming\npm\node_modules\@completium\completium-cli\src\main.js:4214:9)
    at async Proxy.cli (C:\Users\USER\AppData\Roaming\npm\node_modules\@completium\completium-cli\src\cli.js:371:15) {
  shortMessage: 'Command failed with exit code 127: docker run --rm --name my-sandbox --cpus 1 -e block_time=10 --detach -p 20000:20000 oxheadalpha/flextesa:latest jakartabox start',
  command: 'docker run --rm --name my-sandbox --cpus 1 -e block_time=10 --detach -p 20000:20000 oxheadalpha/flextesa:latest jakartabox start',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'a14565de2e3a549640d69675be4ca8b6ae5fe8b25d26d02938ece23501143d31',
  stderr: 'docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "jakartabox": executable file not found in $PATH: unknown.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Command failed with exit code 127: docker run --rm --name my-sandbox --cpus 1 -e block_time=10 --detach -p 20000:20000 oxheadalpha/flextesa:latest jakartabox start
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "jakartabox": executable file not found in $PATH: unknown.
a14565de2e3a549640d69675be4ca8b6ae5fe8b25d26d02938ece23501143d31
```

**Comment by dhruvmalik007** [comment]
Indeed I am also facing the issue . the docker image is successfully pulled from the docker hub but then once we try the command `completium-cli start sandbox` , we get the following : 

```bash
Error: Command failed with exit code 127: docker run --rm --name my-sandbox --cpus 1 -e block_time=10 --detach -p 20000:20000 oxheadalpha/flextesa:latest jakartabox start
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "jakartabox": executable file not found in $PATH: unknown.
b4a4a7bdee055b8e12629d1720da66eba9d3dc9db29398037317549ea6faae6d
    at makeError (/Users/decroissant/.nvm/versions/node/v18.13.0/lib/node_modules/@completium/completium-cli/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/decroissant/.nvm/versions/node/v18.13.0/lib/node_modules/@completium/completium-cli/node_modules/execa/index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startSandbox (/Users/decroissant/.nvm/versions/node/v18.13.0/lib/node_modules/@completium/completium-cli/src/main.js:883:24)
    at async exec (/Users/decroissant/.nvm/versions/node/v18.13.0/lib/node_modules/@completium/completium-cli/src/main.js:4214:9)
    at async Proxy.cli (/Users/decroissant/.nvm/versions/node/v18.13.0/lib/node_modules/@completium/completium-cli/src/cli.js:371:15) {
  shortMessage: 'Command failed with exit code 127: docker run --rm --name my-sandbox --cpus 1 -e block_time=10 --detach -p 20000:20000 oxheadalpha/flextesa:latest jakartabox start',
  command: 'docker run --rm --name my-sandbox --cpus 1 -e block_time=10 --detach -p 20000:20000 oxheadalpha/flextesa:latest jakartabox start',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'b4a4a7bdee055b8e12629d1720da66eba9d3dc9db29398037317549ea6faae6d',
  stderr: 'docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "jakartabox": executable file not found in $PATH: unknown.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by guillaumeduhamel** [comment]
Thank you for your feedbacks, it is fixed in the version `0.4.77`
If you still get `docker` errors, you can run :
```
docker pull oxheadalpha/flextesa:latest
```
